import type { DesktopAction } from './desktop-actions'

export const implementedDesktopActions = [
  'project.add',
  'project.select',
  'project.expand',
  'project.collapse',
  'project.open-in-file-manager',
  'project.reorder',
  'project.pin',
  'project.edit-name',
  'project.refresh-repo-origin',
  'project.archive-threads',
  'project.remove-project',
  'threads.collapse-all',
  'thread.pin',
  'thread.open',
  'thread.archive',
  'thread.archive-many',
  'thread.restore',
  'thread.restore-many',
  'thread.delete',
  'thread.delete-many',
  'thread.new',
  'composer.model',
  'composer.thinking',
  'composer.send',
  'composer.stop',
  'composer.dequeue',
  'composer.reload-settings',
  'composer.answer-native-questions',
  'inbox.mark-read',
  'inbox.dismiss',
  'inbox.clear-read',
  'workspace.commit',
  'workspace.commit-options',
  'workspace.diff-preferences',
  'settings.update',
  'pi-settings.update',
  'projects.import.scan',
  'projects.import.apply',
] as const satisfies readonly DesktopAction[]

export const unimplementedDesktopActions = [] as const satisfies readonly DesktopAction[]
